In [1]:
import pandas as pd
import pybasilica.run as run
import torch
import pyro
import pyro.distributions as dist
import numpy as np
import seaborn as sns
import sklearn.metrics
import torch.nn.functional as F
from tqdm import tqdm
from pyro.distributions import constraints

%load_ext autoreload
%autoreload 2

/Users/elenab/Library/r-miniconda-arm64/envs/basilica-env/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
m_g = pd.read_csv("test_datasets/counts_sbs.N150.G3.csv")
m_sbs = m_g.drop(["groups"], axis=1)
g_sbs = m_g["groups"].tolist() 
cosmic_sbs = pd.read_csv("test_datasets/COSMIC_filt.csv", index_col=0) 

In [3]:
m_g = pd.read_csv("test_datasets/counts_dbs.N150.G3.csv")
m_dbs = m_g.drop(["groups"], axis=1)
g_dbs = m_g["groups"].tolist()
cosmic_dbs = pd.read_csv("test_datasets/COSMIC_dbs.csv", index_col=0) 

In [9]:
obj_sbs = run.fit(
    x=m_sbs, 
    k_list=[3,4], 
    lr=0.005, 
    optim_gamma=0.1,
    n_steps=10, 
    # cluster=[3],
    dirichlet_prior=True,
    # beta_fixed=cosmic_sbs.loc[["SBS1","SBS3","SBS5"]], 
    beta_fixed=None, 
    store_parameters = True, 
    seed_list=[30],
    nonparametric=False,
    store_fits=True, enumer="parallel"
    )


tensor([0.0503, 0.0531, 0.0489, 0.0572, 0.0596, 0.0602, 0.0548, 0.0540, 0.0384,
        0.0546, 0.0600, 0.0577, 0.0277, 0.0598, 0.0544, 0.0602, 0.0333, 0.0505,
        0.0493, 0.0599, 0.0500, 0.0466, 0.0600, 0.0547, 0.0554, 0.0484, 0.0451,
        0.0430, 0.0427, 0.0539, 0.0592, 0.0596, 0.0587, 0.0572, 0.0600, 0.0547,
        0.0461, 0.0570, 0.0590, 0.0405, 0.0596, 0.0010, 0.0451, 0.0198, 0.0387,
        0.0490, 0.0533, 0.0347, 0.0415, 0.0452, 0.0486, 0.0574, 0.0585, 0.0499,
        0.0596, 0.0571, 0.0588, 0.0421, 0.0301, 0.0330, 0.0581, 0.0512, 0.0560,
        0.0522, 0.0528, 0.0571, 0.0370, 0.0464, 0.0571, 0.0471, 0.0598, 0.0394,
        0.0597, 0.0547, 0.0586, 0.0586, 0.0601, 0.0530, 0.0516, 0.0481, 0.0562,
        0.0205, 0.0603, 0.0584, 0.0512, 0.0522, 0.0499, 0.0203, 0.0534, 0.0498,
        0.0602, 0.0588, 0.0457, 0.0292, 0.0328, 0.0584], dtype=torch.float64)
tensor([8.2925e-02, 8.3491e-02, 7.4636e-02, 6.8179e-02, 7.9045e-02, 7.0159e-02,
        8.3040e-02, 8.0228e-02, 7.4556e-02

ELBO 517475.258316: 100%|██████████| 10/10 [00:00<00:00, 256.96it/s]


tensor([3.1137e-02, 3.4252e-02, 3.9206e-02, 3.0953e-03, 3.2210e-02, 4.0169e-02,
        2.8593e-02, 2.5714e-02, 4.0295e-02, 3.4490e-02, 4.0548e-02, 2.6266e-02,
        3.4101e-02, 2.6328e-02, 3.5501e-02, 1.8382e-02, 2.8924e-02, 3.5917e-02,
        4.9846e-03, 2.8537e-02, 5.9632e-03, 3.8399e-02, 2.4667e-02, 2.5719e-02,
        3.2120e-02, 4.0109e-02, 3.4358e-02, 3.3737e-02, 2.2729e-02, 3.0706e-02,
        2.7431e-02, 4.0122e-02, 2.9197e-02, 3.6395e-02, 2.8095e-02, 3.9055e-02,
        3.6465e-02, 2.8912e-02, 3.0426e-02, 3.1055e-02, 3.4264e-02, 2.4961e-02,
        3.4559e-02, 3.7951e-02, 3.8849e-02, 3.1159e-02, 3.9563e-02, 2.1887e-02,
        2.6580e-02, 2.5911e-02, 3.4615e-02, 2.7235e-02, 2.9004e-02, 3.2885e-02,
        3.4944e-02, 3.8456e-02, 3.9298e-02, 3.9465e-02, 3.5315e-02, 3.0378e-02,
        2.6542e-02, 3.5270e-02, 3.6911e-02, 3.9611e-02, 3.2029e-02, 2.8081e-02,
        3.2360e-02, 3.0513e-02, 3.9757e-02, 3.9591e-02, 8.7717e-03, 3.5415e-02,
        1.0109e-02, 3.2769e-02, 3.2934e-

ELBO 592572.610822: 100%|██████████| 10/10 [00:00<00:00, 262.07it/s]

tensor([4.0056e-02, 3.7739e-02, 4.7027e-02, 4.6703e-02, 2.7571e-02, 5.2036e-02,
        5.1639e-02, 4.6796e-02, 3.6085e-02, 5.2143e-02, 4.2200e-02, 3.4912e-02,
        5.1745e-02, 5.2320e-02, 5.2837e-02, 4.9938e-02, 4.7888e-02, 2.6380e-02,
        5.1445e-02, 1.0000e-15, 3.8884e-02, 3.5980e-02, 4.0514e-02, 4.2543e-02,
        4.8708e-02, 4.7649e-02, 4.5560e-02, 4.3775e-02, 3.7948e-02, 4.7396e-02,
        5.2802e-02, 3.1474e-02, 4.2395e-02, 4.9716e-02, 4.8590e-02, 4.8979e-02,
        5.2166e-02, 4.9326e-02, 5.0922e-02, 4.8060e-02, 2.9434e-02, 4.6874e-02,
        2.1835e-02, 5.1306e-02, 2.4297e-02, 3.2849e-02, 2.2356e-02, 2.3116e-02,
        3.1540e-02, 4.4112e-02, 4.3694e-02, 3.5548e-02, 3.7136e-02, 3.7805e-02,
        4.4731e-02, 4.1622e-02, 4.2775e-02, 5.0796e-02, 1.3360e-02, 4.5443e-02,
        4.7086e-02, 5.0344e-02, 4.2444e-02, 5.2808e-02, 5.1092e-02, 5.2406e-02,
        4.7652e-02, 5.2222e-02, 4.3427e-02, 4.0083e-02, 5.2489e-02, 5.2199e-02,
        4.4832e-02, 2.8822e-02, 4.0473e-

In [ ]:
obj_dbs = run.fit(
    x=m_dbs, 
    k_list=3, 
    lr=0.005, 
    optim_gamma=0.1,
    n_steps=1000, 
    # cluster=[3],
    dirichlet_prior=True,
    beta_fixed=cosmic_dbs.loc[["DBS3","DBS5"]], 
    store_parameters=False, 
    seed_list=[30],
    store_fits=True
    )


In [ ]:
input_alpha = [obj_sbs.params["alpha"], obj_dbs.params["alpha"]]
obj_clust = run.fit(
    alpha=input_alpha,
    lr=0.005, 
    # optim_gamma=0.1,
    n_steps=3000, 
    cluster=[6],
    seed_list=[33],
    nonparametric=True,
    store_fits=True,
    autoguide=False
    )


In [ ]:
N, V, K, G = 1, 2, 5, 2

expos = torch.tensor([[[0.298176768, 0.009485776, 0.680553348, 0.007903176, 0.003880932],
                      [0.32536737, 0.31834484, 0.01290994, 0.34337785, 1e-37]]])

centr = torch.tensor([[[2.663226e-01, 1.868571e-01, 1.686374e-01, 4.661891e-09, 3.781830e-01],
                      [9.940815e-02, 7.912397e-02, 7.310225e-01, 9.044534e-02, 3.689002e-27]],
                      [[0.3137514, 0.3310308, 0.1916676, 0.1635502, 1e-37],
                       [4.090709e-01, 5.909291e-01, 5.109680e-11, 7.626013e-09, 1e-37]]])

sf = torch.tensor([[35.59352, 52.37254],
                   [43.17238, 47.30110]])

pi = torch.tensor([0.26591883, 0.07771980])

assert expos.shape == (N, V, K)
assert centr.shape == (V, G, K)
assert sf.shape == (V, G)

thr = 0.01

llik = torch.zeros(G, N)
for g in range(G):
    lprob_alpha = torch.zeros((V, N))
    for v in range(V):
        sf_v = sf[v, g]
        alpha_prior_g = centr[g, v]

        for n in range(N):
            # print(f"n={n}, v={v}, g={g}")
            # print("expos =", expos[n,v,:])
            # print("sf_v =", sf_v)
            idxs_keep = (expos[n,v,:] > thr).nonzero().squeeze()
            # print("idxs =", idxs_keep)
            alpha_n = expos[n,v,idxs_keep] / expos[n,v,idxs_keep].sum()
            # print("alpha_n =", alpha_n)
            alpha_tmp = alpha_prior_g * sf_v
            alpha_c = alpha_tmp[idxs_keep]
            # print("alpha_c =", alpha_c, "\n")
            lprob_alpha[v,n] = dist.Dirichlet(alpha_c).log_prob(alpha_n)

            # print(f"n={n}, v={v}, g={g}")
            # print("expos =", expos[n,v,:])
            # print("sf_v =", sf_v)
            # alpha_n = expos[n,v, :].clone()
            # alpha_n[alpha_n < thr] = 1e-10
            # alpha_n = alpha_n / alpha_n.sum()
            # print("alpha_n =", alpha_n)
            # alpha_c = alpha_prior_g * sf_v
            # print("alpha_c =", alpha_c)
            # lprob_alpha[v,n] = dist.Dirichlet(alpha_c).log_prob(alpha_n)
            # print("lprob_alpha[v,n] =", lprob_alpha[v,n], "\n")

    # sum over independent variants and add log(pi)
    print("lprob_alpha =", torch.sum(lprob_alpha, dim=0))
    llik[g, :] = torch.sum(lprob_alpha, dim=0) + torch.log(pi[g])
    print("llik =", llik[g, :], "\n")

In [ ]:
def logsumexp(weighted_lp) -> torch.Tensor:
    m = torch.amax(weighted_lp, dim=0).unsqueeze(0)  # the maximum value for each observation among the K values
    summed_lk = m[-1] + torch.log(torch.sum(torch.exp(weighted_lp - m), axis=0))
    return summed_lk

ll = logsumexp(llik).unsqueeze(0)
probs = torch.exp(llik - ll)
torch.argmax(probs, dim=0)

In [ ]:
llik

In [ ]:
llik 

In [ ]:
print(obj_clust.params["scale_factor_centroid"])
print(obj_clust.params["z_tau"]) 

In [ ]:
obj_clust.groups

In [ ]:
fitted_grps = obj_clust.groups 
init_grps = obj_clust.init_params["init_clusters"] 
sklearn.metrics.normalized_mutual_info_score(fitted_grps, init_grps) 

In [ ]:
print(np.round(obj_clust.init_params["pi"], decimals=3))
print(np.round(obj_clust.params["pi"], decimals=3)) 

In [ ]:
# sns.pointplot(y=obj_clust.gradient_norms["scale_factor_centroid_param"],
#               x=np.arange(3000)) 
sns.pointplot(y=obj_clust.gradient_norms["AutoDelta.beta_pi"],
              x=np.arange(3000)) 
# sns.pointplot(y=obj_clust.gradient_norms["AutoDelta.latent_class"],
#               x=np.arange(1000)) 

In [ ]:
sns.pointplot(x=np.arange(3000), y=obj_clust.losses) 

In [ ]:
print(obj_clust.groups) 
print(obj_clust.init_params["init_clusters"]) 

In [ ]:
from scipy.optimize import fsolve, minimize_scalar

def _compute_dirichlet_variance(alpha):
    alpha_hat = np.sum(alpha)
    num = alpha * (alpha_hat - alpha)
    denomin = alpha_hat**2 * (alpha_hat + 1)
    return num / denomin

def variance_condition(C, target, alpha):
    variances = _compute_dirichlet_variance(alpha * C)
    # print(f"C={C}, max diff={max(np.abs(variances - target))}")
    return max(np.abs(variances - target))

# Initial guess for C
initial_C = 1
# Calculate the smallest C for the given alpha and Y
alpha = obj_clust.params["alpha_prior"].values[0, :7]
target = obj_clust.init_params["variances"].values[0, :7]

# Solve for C
C_solution = minimize_scalar(fun=variance_condition, method="Bounded", bounds=(1,500), args=(target, alpha))
C_solution.x

In [ ]:
from scipy.optimize import fsolve

def dirichlet_variance(alpha, alpha_hat):
    # alpha_hat = np.sum(alpha)
    num = alpha * (alpha_hat - alpha)
    denomin = alpha_hat**2 * (alpha_hat + 1)
    return num / denomin

def optim_fn(c, true_var, alpha, alpha_hat):
    variances = dirichlet_variance(alpha=alpha*c, alpha_hat=alpha_hat*c)
    return np.abs(true_var - variances) + 1.0


In [ ]:
alpha = dist.Dirichlet(torch.ones(5)).sample().numpy()
true_var = np.ones(5) * 1e-4 
print(f"alpha = {alpha}, true_var = {true_var}")
sols = fsolve(func=optim_fn, x0=1.0, args=(true_var[0], alpha[0], np.sum(alpha))) 

In [ ]:
def solver(target, alpha_hat, alpha_k):
    a = target*alpha_hat**3
    b = target*alpha_hat**2
    c = alpha_k**2 - alpha_k*alpha_hat

    d = np.sqrt(b**2 - 4*a*c)
    xs = np.array([(-b + d) / (2*a), (-b - d) / (2*a)])
    return np.amax(xs)

c = solver(target=true_var[0], alpha_hat=1, alpha_k=alpha[0])

In [ ]:
dirichlet_variance(alpha=alpha, alpha_hat=alpha.sum()) 